version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    networks:
      - backend
    environment:
      POSTGRES_USER: splitwise
      POSTGRES_PASSWORD: splitwise
      POSTGRES_DB: splitwise
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:5.5.3
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
      - backend
    volumes:
      - kafka_data:/var/lib/kafka/data

  application-service:
    build:
      context: .
      dockerfile: DockerfileApplication
    container_name: application-service
    ports:
      - "7000:7000"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - kafka
      - postgres
      - redis
    networks:
      - backend

networks:
  backend:
    external: false
  kafka-net:
    external: false

volumes:
  kafka_data:
    external: false
  redis_data:
    external: false
  database:
    external: false