version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: splitwise
      POSTGRES_PASSWORD: splitwise
      POSTGRES_DB: splitwise
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    external: false
  database:
    external: false