server:
  port: 7000
  servlet:
    context-path: /api/v1


logging:
  level:
    org:
      springframework:
        web: trace
      hibernate:
        type:
          descriptor:
            sql:
              basicBinder: trace
        sql: trace
        orm:
          jdbc:
            bind: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/splitwise?currentSchema=splitwise
    username: splitwise
    password: splitwise

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: splitwise
    show-sql: true


  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true



otp:
  duration:
    120

rest:
  auth:
    /auth/
  idn:
    /idn/

jwt:
  token:
    access:
      expire:
        60
    refresh:
      expire:
        120
  secret:
    access:
      key: 5367566859703373367639792F41S784G468576D5A71347437
    refresh:
      key: 5367566423003373367639792F41S784G468576D5A71345298


springdoc:
  api-docs:
    path: /api-docs